/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author khoi
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnQLGV = new javax.swing.JButton();
        btnQLHS = new javax.swing.JButton();
        btnQLDT = new javax.swing.JButton();
        btnDHS = new javax.swing.JButton();
        btnQLPT = new javax.swing.JButton();
        btnDangXuat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Xin chào:");

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Admin");

        btnQLGV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/teacher_50px.png"))); // NOI18N
        btnQLGV.setText("QL Giáo viên");
        btnQLGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLGVActionPerformed(evt);
            }
        });

        btnQLHS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/stu.png"))); // NOI18N
        btnQLHS.setText("QL Học sinh");
        btnQLHS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLHSActionPerformed(evt);
            }
        });

        btnQLDT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/scorecard_50px.png"))); // NOI18N
        btnQLDT.setText("QL Đề thi");
        btnQLDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLDTActionPerformed(evt);
            }
        });

        btnDHS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exam_50px.png"))); // NOI18N
        btnDHS.setText("QL Điểm HS");
        btnDHS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDHSActionPerformed(evt);
            }
        });

        btnQLPT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/business_building_50px.png"))); // NOI18N
        btnQLPT.setText("QL Phòng thi");
        btnQLPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLPTActionPerformed(evt);
            }
        });

        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDangXuat))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnQLGV)
                        .addGap(18, 18, 18)
                        .addComponent(btnQLHS)
                        .addGap(18, 18, 18)
                        .addComponent(btnQLDT)
                        .addGap(18, 18, 18)
                        .addComponent(btnQLPT)
                        .addGap(18, 18, 18)
                        .addComponent(btnDHS)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addComponent(btnDangXuat))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQLGV)
                    .addComponent(btnQLHS)
                    .addComponent(btnQLDT)
                    .addComponent(btnDHS)
                    .addComponent(btnQLPT))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQLGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLGVActionPerformed
        setVisible(false);
        new QLGiaoVien().setVisible(true);
    }//GEN-LAST:event_btnQLGVActionPerformed

    private void btnQLHSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLHSActionPerformed
        setVisible(false);
        new QLHocSinh().setVisible(true);
    }//GEN-LAST:event_btnQLHSActionPerformed

    private void btnQLDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLDTActionPerformed
        setVisible(false);
        new QLDeThi().setVisible(true);
    }//GEN-LAST:event_btnQLDTActionPerformed

    private void btnQLPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLPTActionPerformed
        setVisible(false);
        new QLPhongThi().setVisible(true);
    }//GEN-LAST:event_btnQLPTActionPerformed

    private void btnDHSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDHSActionPerformed
        setVisible(false);
        new QLDiemHS().setVisible(true);
    }//GEN-LAST:event_btnDHSActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_btnDangXuatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDHS;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnQLDT;
    private javax.swing.JButton btnQLGV;
    private javax.swing.JButton btnQLHS;
    private javax.swing.JButton btnQLPT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
